'use client';

import type { Contract } from '@/types';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { FileText, GanttChartSquare, ListChecks, ShieldAlert, VenetianMask } from 'lucide-react';
import { Label } from '@/components/ui/label';

type ContractAnalysisProps = {
  contract: Contract;
};

export function ContractAnalysis({ contract }: ContractAnalysisProps) {

  const getRiskColor = (score: number) => {
    if (score > 75) return 'bg-destructive';
    if (score > 50) return 'bg-yellow-500';
    return 'bg-green-500';
  };
  const getRiskText = (score: number) => {
    if (score > 75) return 'High Risk';
    if (score > 50) return 'Medium Risk';
    return 'Low Risk';
  }

  const riskScore = contract.aiAnalysis?.riskScore ?? contract.riskScore ?? 0;

  return (
    <Tabs defaultValue="ai-analysis">
      <TabsList className="grid w-full grid-cols-2">
        <TabsTrigger value="ai-analysis">AI Analysis</TabsTrigger>
        <TabsTrigger value="auditor-review">Auditor Review</TabsTrigger>
      </TabsList>
      <TabsContent value="ai-analysis">
        <Card>
          <CardHeader>
            <CardTitle>AI-Powered Report</CardTitle>
            <CardDescription>
              This report is generated by AI and should be used as a guide.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <Card>
              <CardHeader className="pb-2">
                  <div className='flex justify-between items-start'>
                    <div>
                      <CardTitle className="text-lg">Risk Score</CardTitle>
                      <CardDescription>Overall contract risk assessment</CardDescription>
                    </div>
                    
                      <Badge className={`${getRiskColor(riskScore)}`}>{getRiskText(riskScore)}</Badge>
                  </div>
              </CardHeader>
              <CardContent>
                <Progress value={riskScore} className="w-full" indicatorClassName={getRiskColor(riskScore)} />
                  <p className="text-sm text-muted-foreground mt-2">A score of {riskScore}/100 indicates a {getRiskText(riskScore).toLowerCase()} level.</p>
              </CardContent>
            </Card>

            {!contract.aiAnalysis ? (
                <div className="text-center py-10">
                    <p className="text-muted-foreground">AI analysis is not available for this contract yet.</p>
                </div>
            ) : (
            <Accordion type="multiple" defaultValue={['summary', 'risk-assessment']} className="w-full">
              <AccordionItem value="summary">
                <AccordionTrigger><GanttChartSquare className="mr-2 h-5 w-5 text-accent"/>Contract Summary</AccordionTrigger>
                <AccordionContent className="text-base leading-relaxed">{contract.aiAnalysis.summary}</AccordionContent>
              </AccordionItem>
              <AccordionItem value="risk-assessment">
                <AccordionTrigger><ShieldAlert className="mr-2 h-5 w-5 text-accent"/>Risk Assessment</AccordionTrigger>
                <AccordionContent className="text-base leading-relaxed">{contract.aiAnalysis.riskAssessment}</AccordionContent>
              </AccordionItem>
              <AccordionItem value="missing-clauses">
                <AccordionTrigger><ListChecks className="mr-2 h-5 w-5 text-accent"/>Missing Clauses</AccordionTrigger>
                <AccordionContent>
                  <ul className="list-disc pl-5 space-y-2 text-base">
                    {contract.aiAnalysis.missingClauses.map((clause, index) => <li key={index}>{clause}</li>)}
                  </ul>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="recommendations">
                <AccordionTrigger><FileText className="mr-2 h-5 w-5 text-accent"/>Recommendations</AccordionTrigger>
                <AccordionContent className="text-base leading-relaxed">{contract.aiAnalysis.recommendations}</AccordionContent>
              </AccordionItem>
            </Accordion>
            )}

          </CardContent>
        </Card>
      </TabsContent>
      <TabsContent value="auditor-review">
        <Card>
          <CardHeader>
            <CardTitle>Auditor Review & Feedback</CardTitle>
            <CardDescription>
              Professional feedback and annotations from certified auditors.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-4">
              {contract.auditorFeedback && contract.auditorFeedback.length > 0 ? (
                contract.auditorFeedback.map(fb => (
                    <div key={fb.id} className="flex gap-4">
                        <Avatar>
                            <AvatarImage src={fb.auditorAvatarUrl} />
                            <AvatarFallback>{fb.auditorName.slice(0,2)}</AvatarFallback>
                        </Avatar>
                        <div className="flex-1 space-y-1">
                            <div className="flex items-center justify-between">
                                <p className="font-semibold">{fb.auditorName}</p>
                                <p className="text-xs text-muted-foreground">{new Date(fb.timestamp.toDate()).toLocaleString()}</p>
                            </div>
                            <p className="text-sm text-muted-foreground p-3 bg-secondary rounded-lg">{fb.feedback}</p>
                        </div>
                    </div>
                ))
              ) : (
                <div className="text-center py-10 rounded-lg bg-card-darker">
                  <VenetianMask className="mx-auto h-12 w-12 text-muted-foreground" />
                  <h3 className="mt-2 text-sm font-medium">No Auditor Feedback Yet</h3>
                  <p className="mt-1 text-sm text-muted-foreground">The contract is awaiting review by an auditor.</p>
                </div>
              )}
            </div>
            
            <div className="space-y-2 pt-6 border-t">
                 <Label htmlFor="auditor-feedback" className="font-semibold">Add Your Feedback (Auditor)</Label>
                 <Textarea id="auditor-feedback" placeholder="As an auditor, type your feedback here..." className="min-h-[120px]"/>
                 <Button>Submit Feedback</Button>
            </div>
          </CardContent>
        </Card>
      </TabsContent>
    </Tabs>
  );
}
